### ISSUE TITLE
NLog Config doesn't find linked files

### ISSUE THREAD

**Issue by wrwoodman** [NLog/NLog#5045]
In my Visual Studio solution, I have a file named nlogcommon.config that is shared across multiple projects within the solution.   This file is set as a solution item and is shared as a link to projects that wish to consume it.  In the nlog.config file, it is set as an include.
<include file="NLogCommon.config" />
I noticed with an upgrade to 5 that this file was no longer being found during the configuration load.

Under version 4, I found that the config file being loaded was from the bin directory target.  Here's the log entry from the internal logger running under version 4.
```
Info Validating config: Targets=5, ConfigItems=119, FilePath=C:\src4\argo.ecd\src\Argo.ECD.Adapter.Consumer\bin\Debug\netcoreapp3.1\NLog.config
```
Since the included file is copied out to the target directory this did not present a problem and the load happened as expected.

In version 5, the included file no longer loads. In fact, the process crashes.  Looking in the internal log file, I find this entry.
```
Error when including 'NLogCommon.config'. Exception: System.IO.FileNotFoundException: Included file not found: C:\src4\argo.ecd\src\Argo.ECD.Adapter.Consumer\NLogCommon.config
```
Here we find that the process is not looking at the target output directory but in the VS project directory.  Since the file is set as a link the process doesn't find it.

Question: Is there some setting that I can use so that the process looks for files in the target build directory?  

As a workaround, I can use the following code.
```
            var nlogConfig = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "nlog.config");
            LogManager.Configuration = new NLog.Config.XmlLoggingConfiguration(nlogConfig);
            LogManager.ResumeLogging();
```

Question: Is this a bug or by design?

Thanks

**Comment by snakefoot** [comment]
This sounds like a bug, that I would like to investigate.

Would it be possible for you to produce a simple example project that reproduces the issue, and attach it here? (Where upgrade of NLog makes it fail)

**Comment by snakefoot** [comment]
Are you using `NLog.Extensions.Hosting v5` or `NLog.Web.AspNetCore v5` by any chance ?

**Comment by wrwoodman** [comment]
I am using NLog.Web.AspNetCore 5.1.1

**Comment by snakefoot** [comment]
Then I have a good guess what has changed:
- https://github.com/NLog/NLog.Web/pull/749
- https://github.com/NLog/NLog.Extensions.Logging/pull/564

Will make a fix to ensure that ContentRootPath is only used as last priority:

Until available then workaround is changing your Main to this:

```c#
            var logger = LogManager.Setup()
                                   .LoadConfigurationFromAppSettings()
                                   .GetCurrentClassLogger();
            try
            {
                CreateHostBuilder(args).Build().Run();
            }
            catch (Exception exception)
            {
                //NLog: catch setup errors
                logger.Error(exception, "Stopped program because of exception");
                throw;
            }
            finally
            {
                // Ensure to flush and stop internal timers/threads before application-exit (Avoid segmentation fault on Linux)
                NLog.LogManager.Shutdown();
            }
```

**Comment by snakefoot** [comment]
NLog.Web.AspNetCore v5.1.2 has been released, that should fix the issue:

https://www.nuget.org/packages/NLog.Web.AspNetCore/5.1.2

**Comment by wrwoodman** [comment]
I updated to 5.1.2 and removed the workaround.  I have confirmed that this does resolve the issue.
Thank you for your swift response.

**Comment by snakefoot** [comment]
Thank you for the fast confirmation. Will make an unit-test prevent this bug from showing up again.

**Comment by erikbozic** [comment]
Hi @snakefoot
It seems this bug is back starting with the version `5.3.8` of the `NLog.Web.AspNetCore` package.

We link the file from another project like this:
``` xml
  <ItemGroup>
    <None Include="..\..\Shared\Infrastructure\NLog.config" Link="NLog.config"/>
  </ItemGroup>
```

The file is loaded and used in `5.3.7`, but not int `5.3.8` or later.
Calling `LogManager.Setup().LoadConfigurationFromFile()` does work around the issue.

**Comment by snakefoot** [comment]
@erikbozic Please create new issue instead of waking up old issue. You can always add link to old issues if you find them relevant.

Also please include the NLog InternalLogger output at Debug-Level for both the working-version, and latest-version that is failing.

Can see that NLog.Web.AspNetCore ver. 5.3.8 tries improve the support for loading environment-specific NLog.config. See also #1012
